### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by tangbing9922** [Azul-9/DeepLearningEnabledSemanticCommunicationSystems#1]
Where can I get the data in the data_process. py file

**Comment by Azul-9** [comment]
leave your e-mail and I will send u later

**Comment by tangbing9922** [comment]
btang3538@gmail.com   thanks a lot

**Comment by tangbing9922** [comment]
> leave your e-mail and I will send u later

btang3538@gmail.com thanks a lot

**Comment by tangbing9922** [comment]
> leave your e-mail and I will send u later
excuse me,when i run the train_muInfo.py it shows No such file or directory: 'mutual data/x1/12382.npy' 
where can i get the data or how should I make such data
thanks a lot : )

**Comment by hhy875048655** [comment]
> 
> 
> leave your e-mail and I will send u later

Dear Owner, i want to get the data_process.py too, my e-mail 875048655@qq.com  
thank u very much!

**Comment by hellogry** [comment]
Dear Owner, i want to get the dataset too, my e-mail [229602421@qq.com]
thank u very much!

**Comment by YAOxing0205** [comment]
> leave your e-mail and I will send u later
Dear Owner, i want to get the data_process.py too, my e-mail [1023365168@qq.com](mailto:1023365168@qq.com)
thank u very much!

**Comment by hellogry** [comment]
***@***.*** &nbsp; &nbsp; &nbsp; &nbsp;Thanks very much



发自我的iPhone


------------------ Original ------------------
From: YAOxing0205 ***@***.***&gt;
Date: Sun,Apr 3,2022 7:52 PM
To: Azul-9/DeepLearningEnabledSemanticCommunicationSystems ***@***.***&gt;
Cc: hello ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Azul-9/DeepLearningEnabledSemanticCommunicationSystems] about the dataset (#1)





  
leave your e-mail and I will send u later
 Dear Owner, i want to get the data_process.py too, my e-mail ***@***.***
 thank u very much!

**Comment by Tay-wang** [comment]
> 

I want the data in the data_process. py file， my e-mail [2414727785@qq.com]. Thank you very much!

**Comment by adriondragon** [comment]
I want the data in the data_process. py file too， my e-mail [w1739426792@163.com].Thank you very much!

**Comment by Radiantsunshine** [comment]
Dear author, i want to get the data_process.py too, my e-mail [503989460@qq.com]
thank you very much!
Best wishes!

**Comment by Jidi123** [comment]
Dear author, i want to get the data_process.py too, my e-mail 851022055@qq.com
thank you very much!
Best wishes!

**Comment by YijingLin123** [comment]
Dear Author,

Sorry to disturb you. I am a new learner of semantic communication. Would you please send me the data involved in the data_process.py to my email pawn0603@gmail.com?  

Thank you for your help.

Best wishes.

**Comment by hzbhzb666** [comment]
Dear author, i want to get the data_process.py too, my e-mail is [965582246@qq.com]
.
Thank you very much!

**Comment by Jidi123** [comment]
您好，邮件我已收到，会尽快回复，谢谢。

**Comment by starrywongx** [comment]
Dear Author,
I learned a lot from your code which is so clear. But when I run it, I met a problem. Would you please send me the data in the data_process.py to my email （1052211929@qq.com）?
I will really appreciate for your help. 
Best wishes！

**Comment by Jidi123** [comment]
您好，邮件我已收到，会尽快回复，谢谢。

**Comment by starrywongx** [comment]
Dear author,

I have just seen the file "predict_deepSC_without_MI.py" also has some datasets I don't know, like id_dic_10w.pkl， word_dic_10w.pkl，corpus_10w.txt， corpus_10w_train.txt.

Would you please sent it all to me? Or could you please tell me how to make this datasets? I will really appriciate for your help. By the way, the dataset I will just use for study. My email[1052211929@qq.com]

Best wishes!

**Comment by Runzhi-Lu** [comment]
Dear author,

Sorry to disturb you. I am a first-year PhD student working on semantic communication. Thank you very much for sharing the original code of the DeepSC model. Reading it greatly helps me to learn how the model actually works. I would like to enquire if it is possible that I could also have the datasets used by the codes data_process.py and predict_deepSC_without_MI.py? These datasets will be used only for helping me better understand the DeepSC model, and will not be used for other purposes. 
My email is huangxinysu@gmail.com. 

I sincerely appreciate your help! Thank you very much!

**Comment by Radiantsunshine** [comment]
Sorry, I do not have the dataset.


童话果果
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Azul-9/DeepLearningEnabledSemanticCommunicationSystems"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月5日(星期六) 中午1:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Azul-9/DeepLearningEnabledSemanticCommunicationSystems] about the dataset (#1)





 
Dear author,
 
Sorry to disturb you. I am a first-year PhD student working on semantic communication. Thank you very much for sharing the original code of the DeepSC model. Reading it greatly helps me to learn how the model actually works. I would like to enquire if it is possible that I could also have the datasets used by the codes data_process.py and predict_deepSC_without_MI.py? These datasets will be used only for helping me better understand the DeepSC model, and will not be used for other purposes.
 My email is ***@***.***
 
I sincerely appreciate your help! Thank you very much!

**Comment by Monte2345** [comment]
Dear authur, I want to get the dataset just for the study purpose, my e-mail 925166869@qq.com
Thank you very much!

**Comment by NIHAOdroid** [comment]
Dear Author,

I'd like to have a share of the code file. My E-mail is 1198584684@qq.com.
For friends who already have a share of the file, I would appreciate it very much if you could please share it with me.

Thank you!

**Comment by hzbhzb666** [comment]
Several classmates like me who have not received emails have contacted me. I believe that there will be other problems that are difficult to solve alone in the learning process. At present, I have not found an open communication group related to semantic communication, so I have created a new WeChat group dedicated to discussing semantic communication and task oriented communication. I believe we will all benefit from the discussion. **You can add my WeChat (bdhzb1997),** and then I will invite you to join the group. Members of the group are interested in the research of semantic communication, and welcome to join.

**Comment by yuemingqingfeng** [comment]
Dear Author,

Sorry to disturb you. I am a new learner of semantic communication. Would you please send me the data involved in the data_process.py to my email (2587349837@qq.com)?

Thank you for your help.

Best wishes.

**Comment by Jidi123** [comment]
您好，邮件我已收到，会尽快回复，谢谢。

**Comment by zhangbowen1999** [comment]
Sorry to disturb you.I'd like to have a share of the code file. My E-mail is 2764113962@qq.com).Thank you very much!

**Comment by Jidi123** [comment]
您好，邮件我已收到，会尽快回复，谢谢。

**Comment by zjjslch** [comment]
Dear Author,
Would you please send me the data to my email (zjjslch.00@outlook.com)?
Thank you.
Best wish.

**Comment by Jidi123** [comment]
您好，邮件我已收到，会尽快回复，谢谢。

**Comment by E5rr** [comment]
> leave your e-mail and I will send u later

Dear Owner, i want to get the data_process.py too, my e-mail [2265612002@qq.com]
thank u very much!

**Comment by Jidi123** [comment]
您好，邮件我已收到，会尽快回复，谢谢。

**Comment by jsjshe** [comment]
Dear Author,
 could you please send me the data in the data_process.py to my email (2740574341@qq.com)?
 Thank you for your help.

**Comment by Jidi123** [comment]
您好，邮件我已收到，会尽快回复，谢谢。

**Comment by Hakurei123** [comment]
Dear Author,
Could you please send me the datasets to my email (840196927@qq.com)? 
Thank you very much for your help.

**Comment by QH0509** [comment]
Dear Author,
Could you please send me the datasets to my email (1739756418@qq.com)?
Thank you very much for your help.

**Comment by wangmaomao789** [comment]
Dear Author,

Sorry to disturb you. I am a new learner of semantic communication. Would you please send me the data involved in the data_process.py to my email [1071253148@qq.com)?

Thank you for your help.

Best wishes.

**Comment by lupasszhen** [comment]
Dear Author,

Sorry to disturb you. I am a new learner of semantic communication. I queried a lot of corpus datasets and there are no datasets that satisfy data_process.py.Would you please send me the data involved in the data_process.py to my email [3249723967@qq.com)?

Thank you for your help.

Best wishes.

**Comment by zhenyucui11** [comment]
> > leave your e-mail and I will send u later
> > excuse me,when i run the train_muInfo.py it shows No such file or directory: 'mutual data/x1/12382.npy'
> > where can i get the data or how should I make such data
> > thanks a lot : )
  
Would you please send me the data involved in the data_process.py to my email[2908202015@qq.com]?  Thanks

**Comment by Jidi123** [comment]
您好，邮件我已收到，会尽快回复，谢谢。

**Comment by getupgogogo** [comment]
Would you please send me the data involved in the data_process.py to my email[[2825539093@qq.com]? Thanks

**Comment by m-ye** [comment]
Dear Author,
could you please send me the data in the data_process.py to my email [2454720607@qq.com]?
Thank you for your help.

**Comment by Jidi123** [comment]
您好，邮件我已收到，会尽快回复，谢谢。

**Comment by Icexbb** [comment]
could anybody send a copy of the dataset, please?
my email address is xbb@xbb.moe 
Thanks a lot

**Comment by Jidi123** [comment]
您好，邮件我已收到，会尽快回复，谢谢。

**Comment by AndrewQCQC** [comment]
> leave your e-mail and I will send u later

Dear Owner, i want to get the data_process.py too, my e-mail is qianchengnju@126.com, thanks a lot!

**Comment by hankute** [comment]
Dear Author,
could you please send me the data in the data_process.py to my email [1134602569@qq.com]?
Thank you for your help.

**Comment by Jidi123** [comment]
您好，邮件我已收到，会尽快回复，谢谢。

**Comment by BY0416** [comment]
Dear Author,
Could you please send me the datasets to my email ([1833211401@qq.com]）？
Thank you very much for your help！

**Comment by BY0416** [comment]
> leave your e-mail and I will send u later

Dear Author,
Could you please send me the datasets to my email ([1833211401@qq.com])?
Thank you very much for your help！

**Comment by Gilmour109** [comment]
> leave your e-mail and I will send u later
Dear Azul-9,

Sorry to disturb you after such a long time. I just start to learn semantic communication. Would you please send me the data involved in the data_process.py to my email yfzhang109@tju.edu.cn? This means a lot to me.

Thank you sincerely for your help!

Best wishes.

**Comment by Gilmour109** [comment]
> leave your e-mail and I will send u later

Dear Azul-9,

Sorry to disturb you after such a long time. I just start to learn semantic communication. Would you please send me the data involved in the data_process.py to my email [yfzhang109@tju.edu.cn](mailto:yfzhang109@tju.edu.cn)? This means a lot to me.

Thank you sincerely for your help!

Best wishes!

**Comment by Jidi123** [comment]
您好，邮件我已收到，会尽快回复，谢谢。

**Comment by longyiyang** [comment]
Dear author, I want to get the dataset for research purpose only, my email is 878230743@qq.com

**Comment by Jidi123** [comment]
您好，邮件我已收到，会尽快回复，谢谢。
