### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by LLL-ST** [Azul-9/DeepLearningEnabledSemanticCommunicationSystems#5]

**Comment by zhenyucui11** [comment]
问题解决了吗，能分享一下吗？

**Comment by zhenyucui11** [comment]
@LLL-ST

**Comment by JustLiu223** [comment]
I am also having this problem can you share the data file, my email is lggtxl@163.com

**Comment by AndrewQCQC** [comment]
I am also having this problem can you share the data file, my email is qianchengnju@126.com, thanks a lot!
